### ISSUE TITLE
Need python 3 support

### ISSUE THREAD

**Issue by rameshsanth** [vuvova/gdb-tools#10]
The pip package is not working on debian stretch/ubuntu 14.04,
It appears the gdb is packaged with python 3.x (3.5), whereas gdb-tools is still 2.7.
Can this package made available for python 3 as well ?

**Comment by vuvova** [comment]
gdb-tools are compatile with Python 2 and Python 3.

You've installed it for python2, that's why your gdb doesn't see it. Use `pip3` instead of `pip` to install for python 3
