### ISSUE TITLE
ModuleNotFoundError: No module named 'duel' (solution)

### ISSUE THREAD

**Issue by midenok** [vuvova/gdb-tools#12]
Just a quick tip for those who might encounter this error when having both python 2.7 and 3.7 installed. GDB uses python 3 while your `pip` might be from python 2. So before importing `duel` in your .gdbinit.py you might want to add:

```python
sys.path.append("/usr/local/lib/python2.7/dist-packages")
```

Just find out where it was installed:

```
$ pip show gdb-tools
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Name: gdb-tools
Version: 1.3
Summary: Various tools to improve the gdb experience
Home-page: https://github.com/vuvova/gdb-tools
Author: Sergei Golubchik
Author-email: vuvova@gmail.com
License: BSD-3-clause
Location: /usr/local/lib/python2.7/dist-packages
Requires: arpeggio
Required-by:
```

But probably it's a good idea to discard 2.7 like disclaimer says... :)

##### (Feel free to close as this will be searchable in any case)

**Comment by vuvova** [comment]
I'd generally recommend to use `pip3` in such a case and install for python3.

See also #10
