### ISSUE TITLE
Installation instructions are missed

### ISSUE THREAD

**Issue by mkwork** [vuvova/gdb-tools#4]

**Comment by vuvova** [comment]
README says
> put all your python gdb enhancements in ~/.gdb.py and source it from ~/.gdbinit

and later

> Install arpeggio (or copy it into duel/ — it's only 20K) and import duel into your ~/.gdb.py

Basically, it says to put the source tree anywhere you want and to `import duel` module into gdb. Is that not enough?

**Comment by toomuchsalt** [comment]
>  Is that not enough?

Actually it's not. You can't put the source tree in a random place and expect python to locate it.

**Comment by mkwork** [comment]
Oh sorry, looks like I missed this part while there are no Installation header in README :)

**Comment by vuvova** [comment]
@Ritan yes, I thought it's clear that one needs to adjust `sys.path` accordingly. But I'll say that explicitly, thanks.
