### ISSUE TITLE
Duel.py cannot handle dereferencing a pointer in some cases

### ISSUE THREAD

**Issue by darnir** [vuvova/gdb-tools#9]
Within the code I'm debugging, I have an array of pointers to a struct. I'd like to be able to print all the structs in from this array. However, when I attempt a simple print, gdb works, but duel does not. Sample session:

```
(gdb) print *(HOST *)hosts->entry[9]->key
$22 = {scheme = 0x7ffff7bbbb4b "http", host = 0x5555557b4af2 "example.com", robot_job = 0x0, robots = 0x0, queue = 0x0, host_docs = 0x7fffec000b20,
  tree_docs = 0x7fffec005c90, root = 0x7fffec005d70, robot = 0x0, retry_ts = 0, qsize = 0, failures = 0, port = 80, blocked = false}
(gdb) dl *(HOST *)hosts->entry[9]->key
'*'
(gdb) dl (HOST *)hosts->entry[9]->key
(HOST *)hosts->entry[9]->key = 0x5555557b1e90
(gdb)
```

As can be seen, the `hosts->entry` is an array of `HOST *` pointers. With gdb, a print statement is able to dereference the pointer correctly, however with duel, it doesn't seem to work, Is this a bug, or am I using duel wrong?

**Comment by vuvova** [comment]
Is it C or C++?

As far as I remember, gdb is a bit relaxed with casts, what is the correct expression
- `(HOST *)(hosts->entry[9]->key)`
- `((HOST *)(hosts->entry[9]))->key`
or
- `((HOST *)hosts)->entry[9]->key`
?

And if you add parentheses, does duel print it correctly?

**Comment by darnir** [comment]
Oh yes, I should have mentioned, this is C. And also, the correct expression would be `(HOST *)(hosts->entry[9]->key)`

If I remember right, adding the parentheses did not help when I last attempted it. But, let me try once again

EDIT: The adding the parentheses do not help. I just tried it

```
(gdb) p (HOST *)(hosts->entry[9]->key)
$9 = (HOST *) 0x5555557adb70
(gdb) p *(HOST *)(hosts->entry[9]->key)
$10 = {scheme = 0x7ffff7bbc46b "http", host = 0x5555557b08c4 "example.com", robot_job = 0x0, robots = 0x0, queue = 0x0, host_docs = 0x7fffec000b20,
  tree_docs = 0x7fffec000e40, root = 0x7fffe4000cb0, robot = 0x0, retry_ts = 0, qsize = 0, failures = 0, port = 80, blocked = false}
(gdb) dl (HOST *)(hosts->entry[9]->key)
(HOST *)(hosts->entry[9]->key) = 0x5555557adb70
(gdb) dl *(HOST *)(hosts->entry[9]->key)
'*'
```

**Comment by vuvova** [comment]
Okay, I was able to repeat it. Fixing...
Note that if you add another layer of parentheses, it'll work:
```
dl *((HOST *)(hosts->entry[9]->key))
```
and if you enable debugging
```
(gdb) dl debug
```
you'll see a python exception for your first expression.
